name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with pylint
      run: |
        pip install pylint
        pylint python_script.py

    - name: Run Python tests
      run: |
        python test_python_script.py

    - name: Check Rust code format
      run: |
        cd rust_project   # <-- Change to the Rust project directory
        rustup component add rustfmt
        cargo fmt -- --check

    - name: Run Rust tests
      run: |
        cd rust_project   # <-- Change to the Rust project directory
        cargo test
